### ISSUE TITLE
Google VR Update

### ISSUE THREAD

**Issue by anunaykumar** [omgwtfgames/unity-cardboard-photosphere#1]
Google cardboard has now been re-branded as Google VR. Simply replacing the cardboard folder in this project does not works. Can you please update this project to use the latest version of Google VR SDK for Unity (v0.8)

**Comment by omgwtfgames** [comment]
Thanks for the report - I haven't been keeping up with the latest changes in Cardboard / Google VR (too busy developing for SteamVR/OpenVR devices :stuck_out_tongue:). 

It worked for me if I removed the Cardboard folder _and_ the Plugins folder, then imported the latest Google VR for Unity package (as per the [README](https://github.com/omgwtfgames/unity-cardboard-photosphere/blob/master/README.md)).

Anyway, I've taken the opportunity to update everything to use the latest Google VR plugin and tweak a few things - soon Unity will have native Google VR / Daydream support and hopefully I'll be able to remove the extra plugins altogether.
