### ISSUE TITLE
Can't resolve com.goolge.vrtoolkit

### ISSUE THREAD

**Issue by 2ndGAB** [omgwtfgames/unity-cardboard-photosphere#2]
Hello,
I tried to add your project in my own application but `import com.google.vrtoolkit`  fails to resolve vrtoolkit and I don't understand where it comes from.

Strangely, it doesn't prevent Studio to build it and the application works !?!

Could you help me please?

**Comment by 2ndGAB** [comment]
Sorry, problem was caused by a bad dependency

**Comment by omgwtfgames** [comment]
No problem :)
